"""add best_streak

Revision ID: 2fda8b9365a5
Revises: ca170ad5b9c4
Create Date: 2025-11-01 05:19:43.875768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fda8b9365a5'
down_revision: Union[str, Sequence[str], None] = 'ca170ad5b9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('best_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'best_streak')
    # ### end Alembic commands ###
