"""Add last_checked_date

Revision ID: 82da03aea51b
Revises: 0427636dfdb9
Create Date: 2025-11-01 06:05:24.347411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82da03aea51b'
down_revision: Union[str, Sequence[str], None] = '0427636dfdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('last_checked_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'last_checked_date')
    # ### end Alembic commands ###
