"""remove priority

Revision ID: ca170ad5b9c4
Revises: 0e2b46852549
Create Date: 2025-11-01 04:34:34.535372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca170ad5b9c4'
down_revision: Union[str, Sequence[str], None] = '0e2b46852549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
